In [1]:
# Importing the necessary library pandas as pd
import pandas as pd

In [2]:
# RESPONSIBILITY 1: Loading the CSV file into a Pandas DataFrame
data = pd.read_csv("01.Data Cleaning and Preprocessing.csv")

In [3]:
data.shape  # It gives the dimensions of the DataFrame

(324, 23)

In [4]:
data.head() # It print the first 5 rows of the DataFrame

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01

In [5]:
data.tail() # It prints the last 5 rows of the DataFrame

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70
321,9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,66.446,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,58.247,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN

In [6]:
data.info() # It prints a concise summary of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      324 non-null    object
 1   Y-Kappa          324 non-null    float64
 2   ChipRate         319 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         308 non-null    float64
 5   ChipLevel4       323 non-null    float64
 6   T-upperExt-2     322 non-null    float64
 7   T-lowerExt-2     322 non-null    float64
 8   UCZAA            299 non-null    float64
 9   WhiteFlow-4      323 non-null    float64
 10  AAWhiteSt-4      173 non-null    float64
 11  AA-Wood-4        323 non-null    float64
 12  ChipMoisture-4   323 non-null    float64
 13  SteamFlow-4      323 non-null    float64
 14  Lower-HeatT-3    322 non-null    float64
 15  Upper-HeatT-3    322 non-null    float64
 16  ChipMass-4       323 non-null    float64
 17  WeakLiquorF      323 non-null    float64
 18  BlackFlow-2      322 non-null    float64
 19  WeakWashF        323 non-null    float64
 20  SteamHeatF-3     322 non-null    float64
 21  T-Top-Chips-4    323 non-null    float64
 22  SulphidityL-4    173 non-null    float64
dtypes: float64(22), object(1)
memory usage: 58.3+ KB

In [7]:
data.describe() # This display summary statistics for numerical columns

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,324.000000,319.000000,307.000000,308.000000,323.000000,322.000000,322.000000,299.000000,323.000000,173.000000,...,323.000000,322.000000,322.000000,323.000000,323.000000,322.000000,323.000000,322.000000,323.000000,173.000000
mean,20.635370,14.347937,87.464456,1237.837614,258.164483,356.904295,324.020180,1.492010,591.732260,6.140410,...,66.668285,325.567820,300.525699,162.222322,873.828941,1175.917016,263.543068,49.696907,251.240087,30.411671
std,3.070036,1.499095,7.995012,100.593735,87.987452,9.209290,7.621402,0.105923,67.016351,0.081609,...,5.708587,4.609862,4.568484,14.160688,122.073521,149.334010,163.666942,4.551909,1.283432,0.701317
min,12.170000,9.983000,68.645000,0.000000,0.000000,339.168000,284.633000,1.182000,405.111000,5.890000,...,48.568000,318.051000,293.312000,113.922000,486.938000,838.948000,0.000000,35.510000,248.359000,29.010000
25%,18.382500,13.358000,81.823000,1193.215250,213.527000,350.241250,321.420000,1.431500,540.989500,6.089000,...,62.518000,321.385500,296.513250,153.032500,792.019500,1044.817500,134.649000,46.389750,250.312000,29.970000
50%,20.845000,14.308000,86.739000,1273.138500,271.792000,356.843000,325.669000,1.498000,592.895000,6.135000,...,67.429000,324.741000,299.126000,163.690000,865.254000,1150.221500,269.193000,50.277000,251.380000,30.370000
75%,23.032500,15.517000,92.372000,1289.196000,321.680000,362.242250,329.175000,1.560500,639.480500,6.199000,...,71.522000,329.845250,304.244750,172.555000,965.286500,1319.021250,405.563000,53.294250,252.323500,30.820000
max,27.600000,16.958000,121.717000,1351.240000,419.014000,399.135000,337.012000,1.747000,731.394000,6.340000,...,76.147000,333.854000,311.146000,189.268000,1226.277000,1395.767000,715.715000,63.332000,254.122000,32.840000

In [8]:
# Removing duplicate rows from the DataFrame
data = data.drop_duplicates()

data # It displays the contents of the DataFrame named 'data' after removing the duplicates

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29
299,12-10:00,24.98,NaN,85.034,1278.345,368.564,357.723,321.387,NaN,520.365,...,65.729,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47
300,12-11:00,21.00,NaN,88.013,1307.722,278.842,357.438,323.757,NaN,553.070,...,65.795,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,NaN
301,12-12:00,21.40,NaN,85.490,1255.986,273.484,361.365,322.689,NaN,590.199,...,71.456,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46
307,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,71.286,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,NaN

In [9]:
# RESPONSIBILITY 2: Filtering data based on conditions

filtered_data = data[data['ChipRate'] > 16]  # Filter rows where 'ChipRate' is greater than 16
filtered_data # Displays the content after filtering data based on conditions. Here all the rows where 'Chiprate' was greater than 16 got printed.

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020
13,31-12:00,27.20,16.083,82.839,1332.331,366.855,350.094,327.439,1.486,527.893,...,60.271,330.023,302.883,160.562,771.158,1299.974,153.647,47.175,251.767,30.180
14,31-13:00,24.05,16.675,77.025,1284.386,246.336,350.317,329.240,1.538,537.811,...,58.979,329.560,302.146,160.587,823.039,1300.545,372.228,51.740,251.492,NaN
15,31-14:00,25.40,16.425,72.924,1197.775,118.821,350.765,329.799,1.635,585.011,...,65.474,329.773,302.884,175.646,756.154,1300.037,401.418,54.628,251.009,30.410
31,1-06:00,16.10,16.292,68.645,1094.883,245.962,344.478,321.061,1.571,509.786,...,60.236,325.376,301.572,152.409,659.302,1030.210,468.414,48.747,252.169,30.940
47,1-22:00,20.70,16.208,75.314,1220.714,250.234,343.197,321.132,1.475,599.914,...,61.019,319.353,296.842,161.274,618.774,995.344,490.574,47.427,251.879,29.990
57,2-08:00,22.53,16.783,76.396,1281.536,269.496,351.640,324.093,1.556,622.751,...,67.107,319.652,296.317,171.703,776.347,991.185,510.583,49.702,251.548,NaN
63,2-14:00,24.70,16.183,72.611,1231.362,332.497,350.938,322.801,1.455,564.870,...,60.175,319.644,296.799,159.557,670.349,1013.140,461.896,39.376,251.426,29.350
64,2-15:00,25.40,16.958,74.405,1230.776,295.522,350.216,322.740,1.471,540.151,...,52.962,318.913,295.843,146.914,727.366,1052.879,476.150,43.701,252.097,NaN
65,2-16:00,23.50,16.542,80.093,1246.777,198.217,350.521,323.513,1.474,596.506,...,65.556,319.151,296.025,153.147,843.689,1092.750,419.893,48.904,251.345,30.390
69,2-20:00,23.30,16.742,73.689,1233.677,303.943,352.993,323.533,1.464,624.176,...,68.114,321.016,297.472,177.160,766.784,1128.702,448.512,47.535,250.719,29.840
70,2-21:00,21.40,16.482,74.496,1227.821,284.930,354.000,323.818,1.460,620.971,...,66.619,321.598,296.957,173.191,792.281,1125.350,411.826,50.004,250.582,NaN
71,2-22:00,21.50,16.817,78.969,1237.844,285.892,353.644,324.500,1.437,621.887,...,68.750,321.235,296.616,176.460,852.132,1141.946,344.089,52.043,250.678,29.700
72,2-23:00,18.13,16.825,84.836,1246.387,259.527,355.515,325.985,NaN,662.577,...,72.407,321.904,296.185,186.165,810.272,1132.813,0.000,54.044,250.266,29.630
73,3-00:00,18.30,16.833,91.341,1236.911,287.397,356.787,327.856,1.540,661.532,...,71.891,323.285,297.755,187.777,841.552,1144.876,0.000,53.897,250.212,NaN
80,3-07:00,26.50,16.300,75.411,1229.199,358.256,352.871,325.690,1.416,531.174,...,59.183,319.990,296.154,149.077,701.273,1026.333,259.773,42.596,250.775,31.910
81,3-08:00,23.20,16.700,73.381,1225.454,288.327,353.400,325.761,1.532,546.814,...,60.071,319.983,295.603,150.092,784.624,1019.652,453.101,49.500,250.873,NaN
82,3-09:00,24.20,16.458,75.625,1244.665,270.511,355.729,328.243,1.484,611.104,...,70.490,321.568,297.158,171.818,845.316,1037.773,405.866,47.239,250.185,32.020
99,4-02:00,23.50,16.867,76.937,1284.849,334.170,364.132,329.250,1.551,620.208,...,72.448,322.259,297.509,171.093,888.854,1019.068,603.462,50.394,248.435,NaN
100,4-03:00,24.20,16.700,78.434,1287.619,344.674,362.799,328.935,1.553,606.119,...,71.263,321.226,297.391,167.074,940.124,1102.843,598.171,50.595,248.578,31.380
101,4-04:00,17.70,16.417,80.415,1287.981,283.826,363.959,329.097,1.538,627.583,...,71.700,321.005,295.558,166.654,965.555,1118.225,556.742,55.284,248.359,NaN
102,4-05:00,18.00,16.125,79.956,1289.283,66.082,367.427,332.322,1.431,686.279,...,75.067,322.399,295.440,177.999,930.359,1129.319,550.796,56.761,248.496,31.160
110,4-13:00,23.70,16.518,78.458,1277.550,342.110,363.287,325.232,1.433,571.686,...,66.242,320.164,296.907,151.849,789.113,962.725,418.099,41.936,253.700,NaN
111,4-14:00,24.00,16.283,76.717,1262.337,329.827,362.413,325.008,1.501,563.344,...,66.721,319.453,296.084,151.735,858.975,999.078,453.716,43.613,254.122,30.210
112,4-15:00,18.80,16.455,71.679,1191.663,195.725,359.473,326.503,1.480,625.396,...,68.831,319.528,295.052,162.329,1007.466,1017.774,528.605,54.167,253.054,NaN
113,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
114,4-17:00,18.20,16.283,83.508,1288.104,234.284,359.412,328.670,1.534,692.687,...,74.528,321.224,298.231,173.827,854.573,1174.267,62.077,50.653,252.474,NaN
142,5-21:00,16.70,16.250,79.768,1286.259,274.516,359.686,330.501,1.633,691.925,...,73.867,321.979,294.876,171.309,971.862,1126.428,289.993,54.573,250.699,30.546
143,5-22:00,14.80,16.125,81.645,1289.992,323.026,360.474,331.421,1.580,700.114,...,74.096,322.210,294.366,172.555,950.195,1143.910,289.387,54.853,250.444,NaN
150,6-05:00,23.20,16.100,81.242,1283.626,340.045,357.163,324.449,1.501,536.489,...,60.968,321.448,295.154,146.406,1012.146,1040.654,0.000,40.838,252.286,31.660
152,6-07:00,19.78,16.283,80.291,1290.006,197.719,358.333,325.100,1.492,628.143,...,67.361,321.174,293.312,160.638,1122.110,1120.951,309.598,54.990,250.740,30.790
153,6-08:00,19.22,16.067,81.045,1288.618,199.072,360.846,328.080,1.583,703.979,...,72.321,321.930,293.552,175.811,1103.495,1138.627,261.159,56.213,250.007,NaN
168,6-23:00,25.52,16.008,77.070,1285.782,338.656,355.149,325.669,1.462,619.954,...,63.048,320.280,295.959,158.476,878.072,1069.102,264.774,46.030,250.724,NaN
169,7-00:00,24.16,16.683,76.753,1280.487,267.235,355.892,327.226,1.678,621.684,...,64.686,320.424,295.821,159.735,900.706,1085.730,424.195,48.975,250.729,30.415
170,7-01:00,20.40,16.683,76.838,1254.380,199.766,356.899,328.609,1.621,659.068,...,67.931,320.682,295.226,170.355,941.090,1093.449,473.274,55.217,250.790,NaN
171,7-02:00,18.33,16.325,75.644,1234.263,158.626,358.079,330.166,1.650,700.063,...,73.429,320.512,293.925,177.287,863.677,1093.523,445.041,58.004,250.226,30.360
172,7-03:00,16.99,16.317,84.740,1230.147,170.464,359.503,332.017,1.584,723.561,...,74.843,321.274,293.542,181.026,870.849,1118.268,289.171,58.299,249.885,NaN
219,9-02:00,18.50,16.356,84.712,1293.269,167.847,368.170,332.627,1.689,606.323,...,68.023,329.719,304.627,176.218,783.010,1293.493,490.535,56.717,251.630,30.520

In [10]:
# RESPONSIBILITY 3: Handling missing values

# This checks for missing values in the DataFrame. If there is a missing value it returns True else False. 
data.isnull()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
299,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
300,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
301,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [11]:
# This count the number of missing values in each column of the DataFrame
data.isnull().sum()

Observation          0
Y-Kappa              0
ChipRate             4
BF-CMratio          14
BlowFlow            13
ChipLevel4           1
T-upperExt-2         1
T-lowerExt-2         1
UCZAA               24
WhiteFlow-4          1
AAWhiteSt-4        141
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        1
Upper-HeatT-3        1
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          1
WeakWashF            1
SteamHeatF-3         1
T-Top-Chips-4        1
SulphidityL-4      141
dtype: int64

In [12]:
# It check for non-null values in the DataFrame. If there exits a missing value it returns False, else it returns True. 
data.notnull()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
299,True,True,False,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
300,True,True,False,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,False
301,True,True,False,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
307,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False

In [13]:
# It calculates the total number of missing values in the DataFrame
data.isnull().sum().sum()

352

In [14]:
# Filling the missing values in the DataFrame with 0
data2 = data.fillna(value=0)

# Displaying the DataFrame after filling missing values
data2


# NOTE: There are 2 other methods to fill missing values:
# 1. Forward filling (ffill()): Fills missing values with the last observed value in the column.
# 2. Backward filling (bfill()): Fills missing values with the next observed value in the column.
# Example: data3 = data.ffill()  # Forward fill missing values

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,0.00
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,0.00
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,0.000,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29
299,12-10:00,24.98,0.000,85.034,1278.345,368.564,357.723,321.387,0.000,520.365,...,65.729,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47
300,12-11:00,21.00,0.000,88.013,1307.722,278.842,357.438,323.757,0.000,553.070,...,65.795,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,0.00
301,12-12:00,21.40,0.000,85.490,1255.986,273.484,361.365,322.689,0.000,590.199,...,71.456,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46
307,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,71.286,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,0.00

In [15]:
data2.isnull().sum().sum() # Calculates the total number of missing values in the DataFrame data2.

0

In [16]:
# RESPONSIBILTY 4: Calculating summary statistics.

summary_stats = data2.describe()  # Generate descriptive statistics
summary_stats  # Dispalys the summary statistics

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,...,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000
mean,20.568605,14.148123,83.212422,1182.175203,258.504312,355.721296,322.934336,1.371738,591.177498,3.265389,...,66.612525,324.289445,299.383797,161.582003,872.582953,1166.498847,265.220565,49.499538,250.395037,16.193272
std,2.990751,2.212628,19.937140,270.649703,86.798188,22.430183,20.177110,0.417533,75.074486,3.071072,...,6.825301,19.317021,17.924543,16.920268,132.927536,163.596325,163.670998,5.402899,14.538073,15.234571
min,12.170000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18.450000,13.250000,81.045000,1191.338000,215.022000,350.317000,321.519000,1.404000,542.846000,0.000000,...,62.809000,321.226000,296.368000,152.918000,789.113000,1037.773000,138.647000,46.377000,250.287000,0.000000
50%,20.740000,14.308000,85.819000,1254.380000,271.792000,357.163000,325.608000,1.486000,594.218000,6.006000,...,67.678000,323.218000,298.469000,163.512000,868.255000,1144.151000,279.993000,50.132000,251.345000,29.360000
75%,23.000000,15.483000,91.957000,1288.104000,320.890000,362.311000,329.128000,1.556000,642.944000,6.143000,...,71.649000,329.811000,304.220000,172.265000,969.726000,1318.602000,405.866000,53.280000,252.331000,30.420000
max,27.600000,16.958000,121.717000,1351.240000,419.014000,399.135000,337.012000,1.747000,731.394000,6.340000,...,76.147000,333.854000,311.146000,189.268000,1226.277000,1395.767000,715.715000,63.332000,254.122000,32.840000